project:
  type: website
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right:
      - text: Substack
        href: https://montysmusings.substack.com
      - text: LinkedIn
        href: https://linkedin.com/in/sarthakvm
      - text: GitHub
        href: https://github.com/profsarthak

  page-footer:
    left: "© 2026, Sarthak Mohanty"

format:
  html:
    theme: lux
    css: styles.css